---
- name: setup music container
  hosts: orangepi5-plus
  vars:
    container_name: moose
    container_config:
      limits.cpu.allowance: "20%"
      limits.cpu.priority: "8"
    container_devices:
      music:
        path: /music
        source: /home/meepi/music
        type: disk
      navidrome-data:
        path: /var/lib/navidrome
        source: /srv/navidrome
        type: disk
    container_groups: [music_containers]
  roles:
    - containers

- name: setup navidrome
  hosts: music_containers
  roles:
    - role: music
      tags: music
