# This is just an example! Please see available options to customize Navidrome for your needs at
# https://www.navidrome.org/docs/usage/configuration-options/#available-options

LogLevel = "{{ navidrome_config.LogLevel }}"
Scanner.Schedule = "{{ navidrome_config.ScanSchedule }}"
TranscodingCacheSize = "{{ navidrome_config.TranscodingCacheSize }}"
MusicFolder = "{{ navidrome_config.MusicFolder }}"
UIWelcomeMessage = "{{ navidrome_config.UIWelcomeMessage }}"
EnableTranscodingConfig = "{{ navidrome_config.EnableTranscodingConfig }}"
