---
extends: default
rules:
  line-length:
    max: 120
  indentation:
    level: warning
    indent-sequences: consistent
  document-start:
    level: warning
  empty-lines:
    level: warning
  trailing-spaces: enable
